### ISSUE TITLE
TypeError: toggleTrigger is null 	  toggleTrigger.innerHTML = "◄";

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-developer-tools#13] opened 2019-12-31 22:45 UTC
Firebug show this error on this function:

``` js
        self.show = function() {
            slide(0);

            toggleTrigger.innerHTML = "◄";
            toggleTrigger.setAttribute("title", "Hide Toolbar");
            hidden = false;

            cookie.set(cookieKeyHidden, 0);
        };
```

and there is no icon to close toolbar

---

Originally posted by @sjanjic at https://github.com/zendframework/zend-developer-tools/issues/155

**Comment by weierophinney** [comment] 2019-12-31 22:45
What's the error?


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-developer-tools/issues/155#issuecomment-46862601

**Comment by weierophinney** [comment] 2019-12-31 22:45
In javascript, firebug report error


---

Originally posted by @sjanjic at https://github.com/zendframework/zend-developer-tools/issues/155#issuecomment-46862688

**Comment by weierophinney** [comment] 2019-12-31 22:45
Yes, but what error?


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-developer-tools/issues/155#issuecomment-46862750

**Comment by weierophinney** [comment] 2019-12-31 22:45
TypeError: toggleTrigger is null

`toggleTrigger.innerHTML = "◄";`


---

Originally posted by @sjanjic at https://github.com/zendframework/zend-developer-tools/issues/155#issuecomment-46862780

**Comment by weierophinney** [comment] 2019-12-31 22:45
What does [this](https://github.com/zendframework/ZendDeveloperTools/blob/da8a8b232b1b43a43c899f9acf4472ef006b8827/view/zend-developer-tools/toolbar/toolbar.js#L18) look like in your page?


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-developer-tools/issues/155#issuecomment-46862900

**Comment by weierophinney** [comment] 2019-12-31 22:45
How to test it?


---

Originally posted by @sjanjic at https://github.com/zendframework/zend-developer-tools/issues/155#issuecomment-46864752

**Comment by weierophinney** [comment] 2019-12-31 22:45
Just run that command in the console - I suppose the HTML on your page may be broken


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-developer-tools/issues/155#issuecomment-46864820

**Comment by weierophinney** [comment] 2019-12-31 22:45
It shows a element with 'zdf-toolbar-toggle' id but it's hidden


---

Originally posted by @sjanjic at https://github.com/zendframework/zend-developer-tools/issues/155#issuecomment-46866840

**Comment by weierophinney** [comment] 2019-12-31 22:45
`<a href="javascript:void(0);" class="zdf-toolbar-hide-button" id="zdf-toolbar-toggle"></a>`


---

Originally posted by @sjanjic at https://github.com/zendframework/zend-developer-tools/issues/155#issuecomment-46867154

**Comment by samsonasik** [comment] 2020-07-15 14:40
closing since the issue is not reproducible and seems no longer relevant. please re-create issue if problem persist.

**Closed by samsonasik** 2020-07-15 14:40 UTC
